global using SourceGenerators.Commands;
global using SourceGenerators.Common;
global using SourceGenerators.Common.CQRS;
global using SourceGenerators.Common.Service.Helpers;
global using SourceGenerators.Generators;
global using SourceGenerators.Models.Dto;
global using SourceGenerators.Queries;
global using SourceGenerators.Test;
global using System.Text.Json.Serialization;
